<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-26T10:36:58 IST" name="Command line suite" finished-at="2025-07-26T10:36:58 IST" duration-ms="65">
    <groups>
    </groups>
    <test started-at="2025-07-26T10:36:58 IST" name="Command line test" finished-at="2025-07-26T10:36:58 IST" duration-ms="65">
      <class name="logs.ReportDemoTests">
        <test-method signature="failingTest()[pri:0, instance:logs.ReportDemoTests@2f112965]" started-at="2025-07-26T10:36:58 IST" name="failingTest" finished-at="2025-07-26T10:36:58 IST" duration-ms="5" status="FAIL">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at logs.ReportDemoTests.failingTest(ReportDemoTests.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at logs.RunTestsProgrammatically.main(RunTestsProgrammatically.java:14)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failingTest -->
        <test-method signature="testAddition()[pri:0, instance:logs.ReportDemoTests@2f112965]" started-at="2025-07-26T10:36:58 IST" name="testAddition" finished-at="2025-07-26T10:36:58 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddition -->
        <test-method signature="testSubtraction()[pri:0, instance:logs.ReportDemoTests@2f112965]" started-at="2025-07-26T10:36:58 IST" name="testSubtraction" finished-at="2025-07-26T10:36:58 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSubtraction -->
        <test-method signature="skippedTest()[pri:0, instance:logs.ReportDemoTests@2f112965]" started-at="2025-07-26T10:36:58 IST" name="skippedTest" finished-at="2025-07-26T10:36:58 IST" depends-on-methods="logs.ReportDemoTests.failingTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method logs.ReportDemoTests.skippedTest() on instance logs.ReportDemoTests@2f112965 depends on not successfully finished methods 
[logs.ReportDemoTests.failingTest() on instance logs.ReportDemoTests@2f112965]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method logs.ReportDemoTests.skippedTest() on instance logs.ReportDemoTests@2f112965 depends on not successfully finished methods 
[logs.ReportDemoTests.failingTest() on instance logs.ReportDemoTests@2f112965]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at logs.RunTestsProgrammatically.main(RunTestsProgrammatically.java:14)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- skippedTest -->
      </class> <!-- logs.ReportDemoTests -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
